2024-01-17 17:45:47,675 INFO    MainThread:50336 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-17 17:45:47,675 INFO    MainThread:50336 [wandb_setup.py:_flush():76] Configure stats pid to 50336
2024-01-17 17:45:47,675 INFO    MainThread:50336 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Admin\.config\wandb\settings
2024-01-17 17:45:47,675 INFO    MainThread:50336 [wandb_setup.py:_flush():76] Loading settings from d:\งาน\AR_classification\wandb\settings
2024-01-17 17:45:47,675 INFO    MainThread:50336 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-17 17:45:47,675 INFO    MainThread:50336 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-17 17:45:47,676 INFO    MainThread:50336 [wandb_init.py:_log_setup():526] Logging user logs to d:\งาน\AR_classification\wandb\run-20240117_174547-leb4b499\logs\debug.log
2024-01-17 17:45:47,676 INFO    MainThread:50336 [wandb_init.py:_log_setup():527] Logging internal logs to d:\งาน\AR_classification\wandb\run-20240117_174547-leb4b499\logs\debug-internal.log
2024-01-17 17:45:47,676 INFO    MainThread:50336 [wandb_init.py:init():566] calling init triggers
2024-01-17 17:45:47,676 INFO    MainThread:50336 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'architecture': 'CNN', 'dataset': 'Organization', 'epochs': 200, 'weightname': 'res_6', 'num_step_per_epoch': 1}
2024-01-17 17:45:47,676 INFO    MainThread:50336 [wandb_init.py:init():591] re-initializing run, found existing run on stack: xv104xy6
2024-01-17 17:45:47,678 INFO    MainThread:50336 [wandb_run.py:_finish():1962] finishing run newturno/AR-classification/xv104xy6
2024-01-17 17:45:47,678 ERROR   MainThread:50336 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-01-17 17:45:47,678 INFO    MainThread:50336 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-17 17:45:47,678 INFO    MainThread:50336 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-01-17 17:45:47,678 INFO    MainThread:50336 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-17 17:45:47,679 INFO    MainThread:50336 [wandb_run.py:_restore():2185] restore
2024-01-17 17:45:47,679 INFO    MainThread:50336 [wandb_run.py:_restore():2191] restore done
